### ISSUE TITLE
Gini-sensitive sublinear voting power

### ISSUE THREAD

**Issue by ckxpress** [desmos-labs/introduction#1]
Awesome. i thought about that in LikeChain too. Diminishing voting power. Such as taking a square root. And your proposal looks *very* interesting. Why don't you include an example with Gini coefficient similar to Hong Kong 2018 though ;)

But i won't implement that in LikeChain from the start. As i've mentioned, i'd like to have it kicked off first, then have the validators themselves govern the future of LikeChain. i may raise a proposal later to implement _Gini-sensitive sublinear voting power_ and we'll see how it goes.

**Comment by terencesflam** [comment]
We have modified our thought again as we have found another more interesting way for our tokenomics: fixed inflation amount and same reward to each validator. But we are still considering what role of Gini coeffcient can play in our tokenomics.
